### ISSUE TITLE
Please create an issue in English

### ISSUE THREAD

**Issue by renmm** [didi/pile.js#1]
Pile.js的目标是成为一个全球性的项目。 我们必须选择一种语言，几乎每个人都可以知道它，以便我们可以相互沟通。 那么应该选择哪种语言，中文还是英文？当然，我认为本地化也很重要。可以添加QQ 或者建设中文论坛？

Pile.js want to be a global project. We have to chose one language almost everyone could know it so that we can communicate each other. So which languages should be chosen, Chinese or English? Of course, I think localization is also important, add QQ or build a Chinese forum ?

**Comment by gaiazhang** [comment]
Well. Quite right, the important strategy of internationalization.

**Comment by zhangjingwei** [comment]
that's cool ！
may be we can use english for the external communication , but under normal circumstances, it is more convenient to use the mother tongue (chinese).
