### ISSUE TITLE
Rule component

### ISSUE THREAD

**Issue by font-end-newbie** [didi/pile.js#13]
不好意思我已经知道如何引用pile了，可是rule组件没明白，我已经传值进去了，还是没有办法看到刻度尺下的数字，是list数组的原因吗？具体该怎么传呢

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by renmm** [comment]
import Rule from 'pile/dist/components/rule'
const  {RuleLine} = Rule

<RuleLine 
	list={[{name:"20kg",value:20},{name:"40kg",value:40},{name:"60kg",value:60},{name:"80kg",value:80},{name:"100kg",value:100},{name:"120kg",value:120},{name:"140kg",value:140},{name:"160kg",value:160},{name:"180kg",value:180},{name:"200kg",value:200},{name:"220kg",value:220},{name:"240kg",value:240},{name:"260kg",value:260}]}
	defaultValue={75}
	touchMin={40} 
	touchMax={240} 
	min={20} 
	max={300}
	back={(o)=> { console.log(`${o.value}kg`)}}
 />

线上examples:  https://didi.github.io/pile.js/demo/#/rule?_k=0j56e6

或者你拉取项目的1.x分支，查看里面的exmaples代码。

@font-end-newbie

**Comment by webyansen** [comment]
麻烦把你传的参数发一下，谢谢
