### ISSUE TITLE
Too many useless logs in console

### ISSUE THREAD

**Issue by jacks808** [didi/pile.js#5]
Too many logs in console:
![](https://ws3.sinaimg.cn/large/006tKfTcly1fr3xjfymlij313m068mxp.jpg)
![](https://ws3.sinaimg.cn/large/006tKfTcly1fr3xirstg8j312y07mt9l.jpg)
![](https://ws1.sinaimg.cn/large/006tKfTcly1fr3xi4fvn3j313e096wg2.jpg)
![](https://ws4.sinaimg.cn/large/006tKfTcly1fr3xh90q8sj313601yglm.jpg)

**Comment by renmm** [comment]
Which component is specifically referring to?

**Comment by yansenfe** [comment]
Because these console are exported on the example page, in order to let everyone see the effect, we do not need to correct it for the time being.

**Comment by jacks808** [comment]
At least offer a switch to turn log off.

**Comment by jacks808** [comment]
Why close?
